(ns ant-man.antd)

;; Simple utility library for the Ant Design React library
;; https://ant.design/

(def components
  '[Affix
    Alert
    Anchor
    Anchor.Link
    AutoComplete
    AutoComplete.OptGroup
    AutoComplete.Option
    Avatar
    BackTop
    Badge
    Breadcrumb
    Breadcrumb.Item
    Button
    Button.Group
    Calendar
    Card
    Card.Grid
    Card.Meta
    Carousel
    Cascader
    Checkbox
    Checkbox.Group
    Col
    Collapse
    Collapse.Panel
    DatePicker
    DatePicker.MonthPicker
    DatePicker.RangePicker
    DatePicker.WeekPicker
    Divider
    Drawer
    Dropdown
    Dropdown.Button
    Form
    Form.Item
    Icon
    Input
    Input.Group
    Input.Search
    Input.TextArea
    InputNumber
    Layout
    Layout.Content
    Layout.Footer
    Layout.Header
    Layout.Sider
    List
    List.Item
    List.Item.Meta
    LocaleProvider
    Mention
    Mention.Nav
    Menu
    Menu.Divider
    Menu.Item
    Menu.ItemGroup
    Menu.SubMenu
    Modal
    Pagination
    Popconfirm
    Popover
    Progress
    Radio
    Radio.Button
    Radio.Group
    Rate
    Row
    Select
    Select.OptGroup
    Select.Option
    Slider
    Spin
    Steps
    Steps.Step
    Switch
    Table
    Table.Column
    Table.ColumnGroup
    Tabs
    Tabs.TabPane
    Tag
    Tag.CheckableTag
    TimePicker
    Timeline
    Timeline.Item
    Tooltip
    Transfer
    Tree
    TreeSelect
    TreeSelect.TreeNode
    Tree.TreeNode
    Upload])

